### ISSUE TITLE
All the Scalatest examples and documentation are out of date

### ISSUE THREAD

**Issue by Azuaron** [allure-examples/allure-scalatest-example#3]
This Scalatest example and the [documentation](https://docs.qameta.io/allure/#_scalatest) are out of date with regard to using Scalatest and Allure. They reference the library "ru.yandex.qatools.allure" % "allure-scalatest_2.10", but the latest Scalatest library is "io.qameta.allure" % "allure-scalatest_2.12". They also reference the class `ru.yandex.qatools.allure.scalatest.AllureReporter`, but there is no AllureReporter class in the new Scalatest library.

Could you update the examples and documentation for how to use Allure with Scalatest?

**Comment by 5hawnknight** [comment]
Any update on this issue? Is Scala/Scalatest supported?
